In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
usersDF = pd.read_csv("/content/drive/MyDrive/users.csv")
usersDF.head()

  Country or area           Subregion    Region Internet users     Population
0           China        Eastern Asia      Asia  1,010,740,000  1,427,647,786
1           India       Southern Asia      Asia    833,710,000  1,352,642,280
2   United States    Northern America  Americas    312,320,000    327,096,265
3       Indonesia  South-eastern Asia      Asia    196,000,000    267,670,543
4          Brazil       South America  Americas    160,010,801    209,469,323

In [ ]:
# Number of unique countries and continents
print(len(usersDF["Country or area"].unique()))

214

In [ ]:
# Class defined by the challenge description
class MapWithContinent:
  continentMap = {}

  def mapping(self, df: pd.DataFrame, countryCol: str, continentCol: str):
    countries = df[countryCol].tolist()
    continents = df[continentCol].tolist()

    for idx, country in enumerate(countries):
      self.continentMap[country] = continents[idx]

  def getContinent(self, country: str):
    try:
        return self.continentMap[country]
    except:
        print(f"There's no country called { country } in our base")
        return None

In [ ]:
countriesMap = MapWithContinent()
countriesMap.mapping(usersDF, "Country or area", "Region")
countriesMap.getContinent("Brazil")

'Americas'

In [ ]:
speedsDF = pd.read_csv("/content/drive/MyDrive/avgspeed.csv", header=0, names=["Country", "Avg Speed"])
speedsDF.head()

       Country  Avg Speed
0       Canada      75.18
1  South Korea     117.95
2  Netherlands     108.33
3        Japan      44.05
4       Norway     134.73

In [ ]:
# Adds column Continent to speeds dataframe
speedsDF['Continent'] = speedsDF.apply(lambda row: countriesMap.getContinent(row["Country"]), axis=1)
speedsDF.head()

print(speedsDF["Continent"].isna().sum()) # Number on null continents
print(speedsDF["Continent"].count())      # Number of valid continents
print(speedsDF["Avg Speed"].mean())       # Gets the avg speed acroos all countries
print(speedsDF.groupby(["Continent"])["Avg Speed"].mean()) # Gets the avg speed by continet

There's no country called Hong Kong in our base
There's no country called Puerto Rico in our base
There's no country called Ivory Coast in our base
There's no country called Macau in our base
There's no country called Kosovo in our base
There's no country called DR Congo in our base
6
138
36.36727272727273
Continent
Africa      17.792800
Americas    24.131154
Asia        38.219333
Europe      54.161282
Oceania     50.666667
Name: Avg Speed, dtype: float64

In [ ]:
# Reads new instance of users
newUsersDF = pd.read_csv("/content/drive/MyDrive/users.csv")
print(newUsersDF["Internet users"].isna().sum())
print(newUsersDF["Population"].isna().sum())

# Drop null values
newUsersDF.dropna(inplace=True)
print(newUsersDF["Internet users"].isna().sum())
print(newUsersDF["Population"].isna().sum())

0
2
0
0

  Country or area           Subregion    Region  Internet users  Population
0           China        Eastern Asia      Asia      1010740000  1427647786
1           India       Southern Asia      Asia       833710000  1352642280
2   United States    Northern America  Americas       312320000   327096265
3       Indonesia  South-eastern Asia      Asia       196000000   267670543
4          Brazil       South America  Americas       160010801   209469323

In [ ]:
# Converts column from str to int
newUsersDF["Internet users"] = newUsersDF["Internet users"].apply(lambda x: x.replace(',', ''))
newUsersDF["Internet users"] = newUsersDF["Internet users"].astype(int)

# Converts column from str to int
newUsersDF["Population"] = newUsersDF["Population"].apply(lambda x: x.replace(',', ''))
newUsersDF["Population"] = newUsersDF["Population"].astype(int)

newUsersDF.head()

In [ ]:
# Get countries where more than 90% of the population has access to the internet
bigAccessDF = newUsersDF[newUsersDF["Internet users"] > (newUsersDF["Population"] * 0.9)]
bigAccessDF.count()

Country or area    15
Subregion          15
Region             15
Internet users     15
Population         15
dtype: int64

In [ ]:
# Get countries where less than 10% of the population has access to the internet
smallAccessDF = newUsersDF[newUsersDF["Internet users"] < (newUsersDF["Population"] * 0.1)]
smallAccessDF.count()

Country or area    7
Subregion          7
Region             7
Internet users     7
Population         7
dtype: int64